type: chart
configs:
  - chart: logging-central
    release: logging-central
    test:
      values:
    stage:
      values:
helmRepos:
   - name: cnct-migrations
     url: http://charts.migrations.cnct.io
prod:
  doDeploy: none
  #doDeploy: versionfile
